### PR TITLE
Add Figure 1

### PR DESCRIPTION
**Pull request by jenna-tomkinson**
# Add Figure 1

In this PR, figure 1 for the manuscript has been created in R using patchwork. Panel A is generated in the notebook, and Panel B is created in BioRender and saved as PNG.

### CODE REVIEW

**Comment by gwaybio** [comment]
It's a really nice figure! 🎉 

Here are a couple nitpicks:

## Panel A

- The text is a bit small, particularly the axis labels, the axis tick labels, the legend title, and the legend text.
- Please make sure to use consistent capitalization (e.g., the legend title, `Phenotype Category` should be `Phenotype category`, `Single Cell Counts` should be `Single cell counts`, y axis title as well.) The mitocheck phenotype classes themselves do not need to be changed! (except probably make text a bit bigger)
- The colors clash a bit with the style of the other figures. Can you make them a bit more dynamic rather than the default colors? I wouldn't use Figure 2A colors directly, but perhaps can be used as an inspiration.

## Panel B

- This is looking really nice!
- Please use consistent capitalization (e.g., `Image Analysis` -> `Image analysis`) - use a keen eye for these details!
- To keep colors consistent across the manuscript, can you match the CP, DP and Both files to the colors in Figure 3B
- The platemap in the Image-based profiling section has a color range from green to purple. Does this mean anything? If not, then I would remove it to reduce potential confusion.
- Increase the font size in the axis labels in the normalize data plot, if it is important detail. If it is not important detail, remove the text.
- The text for the normalize data can be simplified. How about: "Normalize data with negative control cells".
- To better manage space in the Machine learning panel, you can put the split data text on the same line.
- Can you. make "Predictions" read "Phenotype predictions' to increase clarity?
- The cell and squigly line are a bit confusing. What is the squigly? Is ther another obvious phenotype in biorender? Perhaps some mitosis phase?
- Please increase font size of precision recall curve
- I am a bit confused by the Assess Generalizability panel - I think this one needs the most work.
- Specifically: 1) I'm not sure what the ellipses (`...`) and training data represents in LOIO. 2) It's unclear why there is an arrow that points from LOIO to the JUMP analysis, maybe the JUMP analysis deserves it's own box under the same "generalizability" header? 3) It is unclear why it is important to show with a cartoon that there are 51 plates (it takes up a lot of space). Why not just say `JUMP-CP Pilot (51 plates)`> (4) inrease font size in jump umap;

## General

- The plot tag annotations (`A` / `B`) are a bit small
- There could be some whitespace management improvements comparing A to B. A is quite long, and B doesn't align with A. Perhaps this is because B is being saved with excess whitespace?

Happy to give this another look after the second iteration!

**Comment by jenna-tomkinson** [comment]
Here is what I have implemented based on your review:

## Panel A

1. Increased text size (please let me know if these need to be increased more)
2. Changed capitalization to keep consistent but didn't change the x-axis title due to this statement: "The mitocheck phenotype classes themselves do not need to be changed!". Let me know if I misinterpreted this and I will also update this title too for capitalization.
3. I changed to the `Dark2` palette from RColorBrewer. I think it clashes less, but please let me know if this should be changed as well. Here is also the link to the different palettes if you see one that would be better: https://r-graph-gallery.com/38-rcolorbrewers-palettes.html. 

## Panel B (likely will need font increased)

1. Updated to use consistent capitalization
2. Matched colors for CP, DP, and Both
3. Fixed plate map
4. Removed text from normalization example figure
5. Updated normalization statement
6. Updated Machine learning plot
7. Tried to improve the generalizability section, just struggling with how to simply visualize what we need. This definitely still needs work so in your next review I would love more suggestions.

## General

Made the tags much bigger and fixed the alignment issue/whitespace issue by making the plot "free" per the documentation to avoid patchwork from trying to align itself.

I look forward to more improvements after your next review!

**Comment by gwaybio** [comment]
More nitpicks:

## Panel A

- You have enough space to spell out "consequences"
- No hyphen needed in "single-cell" (y axis title)
- Mitocheck Phenotype Class -> Mitocheck phenotype class (x axis title) (I meant the axis tick labels were ok in capitalization since they are the names given by mitocheck)
- Everything else looks great!

## Panel B

- There could be some potential for confusion in the mitocheck frames (three images offset) compared to the LOIO 4 images offset. This is super minor, so please ignore if you disagree, but is there a way to make the LOIO visualization a bit more clear? Maybe have four images, three of them circled as "training" and the other with an ❌ and some sort of arrow pointing to the ❌ saying "evaluation"? 🤷 
- There are currently two arrows pointing from the nucleus in Image analysis that point to Granularity and Intensity. Are there other more general categories to highlight? We extract more than this right? maybe also add the number of features we extract: `Extract nuclei features (257)` (I don't remember if this is the actual number or not, I just took a guess!)
- I love the colors of CP DP and both! Can you also update these colors in the normalize cells portion (I see the curves are the right color, but not the files)
- The colors for the training and test are very similar to the DP and Both colors, consider using a different color scheme here.
- Consider making capitalization consistent in "Precision-Recall Curves" -> "Precision-recall curves"
- Consider adding a legend in the PR curves showing that dotted lines is random shuffle and solid lines is real data. This will also make the plot square, which is how I'm used to seeing PR curves!
- The UMAP in the JUMP panel: 1) Consider using the same CP color file scheme (green); 2) Morphology Space -> morphology space (capitalization) 3) You might consider saving white space by saying "Single-cell morphology UMAP" (avoid 2 lines) 4) The text is kind of a lot - maybe just "Evaluate performance of phenotype prediction in JUMP" 🤷

**Review by gwaybio — APPROVED** [review]
Looks great Jenna! Happy to review again for a round 3, but I will go ahead and approve so you can merge when you're happy.

Before merging, please also add this figure to the README in this PR - it is a great representation of our project which we want to highlight :)

**Comment by jenna-tomkinson** [comment]
main_figure_1_class_count_and_workflow(1)

Figure 1: Class counts and workflow

**Comment by jenna-tomkinson** [comment]
@gwaybio Thank you lots for the review! This was a great first exercise with patchwork and I am excited to work more on creating figures! I will be merging now after addressing your comments, but please feel free to let me know if anything else needs to be updated.

**Pull request merged**
